### ISSUE TITLE
Conflict information between two branches

### ISSUE THREAD

**Issue by bennekrouf** [lesfurets/git-octopus#1]
I am trying to use octopus script. My script tries to merge several branch named "PLD*". When a conflict occurs between master and another branch, I have the detail of the conflict... But when it is a conflict between 2 branches, I have not the information of the "from branch". 

Do you know how to get information or what's is the problem ?

Help appreciated !

**Comment by apflieger** [comment]
There is no automated way to know that currently but you can guess by reading which branch he was trying to merge : there's a log (Trying simple merge with refs/heads/PLDsomething) before the ERROR occurs. Once you have the branch, just checkout on it and retry the octopus. This time the current branch should have conflicts with an other one.
