### ISSUE TITLE
shasum equivalent for windows ?

### ISSUE THREAD

**Issue by HadrienPierart** [lesfurets/git-octopus#10]
Hi there !
Just read quickly the docs and noticed that you were mentionning installation on windows required having a `shasum` installed. Does this even exist on windows ?
Have you tried this tool on windows already ? (Im not on windows myslef, but sometimes, adoption can rely on a more windows friendly tool !)

Also, I just read on StackOverFlow that there was a cksum equivalent named `CertUtil`. Have you tried it ?
http://stackoverflow.com/questions/12276426/windows-equivalent-of-linux-cksum-command

(in case you plan to ensure windows support)

**Comment by apflieger** [comment]
At LesFurets.com we have 2 people using git-octopus on windows so yes, it works.
As far as I remember, it can run on both cygwin/git and powershell/msysgit.
There is a shasum.exe as well that has the same contract than the unix shasum so we just had to rename it shasum.exe -> shasum. But I don't remember if it was cygwin specific.

**Comment by HadrienPierart** [comment]
Ok ! Thx for the explanation then !
