### ISSUE TITLE
shouldn't be installed to /usr/local

### ISSUE THREAD

**Issue by YOUR1** [lesfurets/git-octopus#18]
If you install git-octopus to /usr/local jenkins won't be able to find the executable. Symlinking/moving the bin to /usr/bin/ will solve the problem.

**Comment by apflieger** [comment]
Hi!
This means that `/usr/local/bin` is not in your $PATH. It should be the case on most operating systems. Which one are you using ?

Note that the makefile follows [GNU standards](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html#Directory-Variables) so you can override the default value of `prefix` (`/usr/local`) like this

```
make install prefix="/usr"
```
