### ISSUE TITLE
proper use of conflict resolution ?

### ISSUE THREAD

**Issue by durzo** [lesfurets/git-octopus#23]
Hi, I'm a bit confused on the proper way to resolve conflicts.

I am merging 9 branches and there is a conflict between two. I created a conflict resolution using `git conflict` but octopus still fails unless i specify the resolution ref in my command line arguments:

```
$ git octopus origin/myproject/FEATURE-* origin/myproject/base
Branches beeing merged :
	refs/remotes/origin/myproject/FEATURE-1
	refs/remotes/origin/myproject/FEATURE-2
	refs/remotes/origin/myproject/FEATURE-3
	refs/remotes/origin/myproject/FEATURE-4
	refs/remotes/origin/myproject/FEATURE-5
	refs/remotes/origin/myproject/FEATURE-6
	refs/remotes/origin/myproject/FEATURE-7
	refs/remotes/origin/myproject/FEATURE-8
	refs/remotes/origin/myproject/base
-----------------------------------------------------------
Fast-forwarding to: refs/remotes/origin/myproject/FEATURE-1
Trying simple merge with refs/remotes/origin/myproject/FEATURE-2
Trying simple merge with refs/remotes/origin/myproject/FEATURE-3
Trying simple merge with refs/remotes/origin/myproject/FEATURE-4
Trying simple merge with refs/remotes/origin/myproject/FEATURE-5
Simple merge did not work, trying automatic merge.
Auto-merging lib/moodlelib.php
Trying simple merge with refs/remotes/origin/myproject/FEATURE-6
Simple merge did not work, trying automatic merge.
Auto-merging lib/moodlelib.php
Auto-merging lib/setuplib.php
ERROR: content conflict in lib/setuplib.php
Added local/filestorage/classes/file_storage/file_system.php in both, but differently.
ERROR: content conflict in local/filestorage/classes/file_storage/file_system.php
Added local/filestorage/lang/en/local_filestorage.php in both, but differently.
ERROR: content conflict in local/filestorage/lang/en/local_filestorage.php
Added local/logging/classes/logger.php in both, but differently.
ERROR: content conflict in local/logging/classes/logger.php
Added local/logging/classes/monolog/fluenthandler.php in both, but differently.
ERROR: content conflict in local/logging/classes/monolog/fluenthandler.php
Added local/logging/db/tasks.php in both, but differently.
ERROR: content conflict in local/logging/db/tasks.php
Added local/logging/lang/en/local_logging.php in both, but differently.
ERROR: content conflict in local/logging/lang/en/local_logging.php
Added local/logging/version.php in both, but differently.
ERROR: content conflict in local/logging/version.php
fatal: merge program failed
Applying conflict resolution 069594f00ab6213b53e1bc2c37305c812223c12d
Trying simple merge with refs/remotes/origin/myproject/FEATURE-7
fatal: You need to resolve your current index first
-----------------------------------------------------------
Testing merges one by one with myproject/base...

merging refs/remotes/origin/myproject/FEATURE-1 ... SUCCESS
merging refs/remotes/origin/myproject/FEATURE-2 ... SUCCESS
merging refs/remotes/origin/myproject/FEATURE-3 ... SUCCESS
merging refs/remotes/origin/myproject/FEATURE-4 ... SUCCESS
merging refs/remotes/origin/myproject/FEATURE-5 ... SUCCESS
merging refs/remotes/origin/myproject/FEATURE-6 ... SUCCESS
merging refs/remotes/origin/myproject/FEATURE-7 ... SUCCESS
merging refs/remotes/origin/myproject/FEATURE-8 ... SUCCESS
-----------------------------------------------------------
No conflicts found between myproject/base and the rest of the branches
OCTOPUS FAILED
```

If i use the conflict reference ID it works, but the documentation indicates that this isn't required, or is it ??

```
$ git octopus origin/myproject/FEATURE-* origin/myproject/base 069594f00ab6213b53e1bc2c37305c812223c12d
Branches beeing merged :
	refs/conflicts/069594f00ab6213b53e1bc2c37305c812223c12d
	refs/remotes/origin/myproject/FEATURE-1
	refs/remotes/origin/myproject/FEATURE-2
	refs/remotes/origin/myproject/FEATURE-3
	refs/remotes/origin/myproject/FEATURE-4
	refs/remotes/origin/myproject/FEATURE-5
	refs/remotes/origin/myproject/FEATURE-6
	refs/remotes/origin/myproject/FEATURE-7
	refs/remotes/origin/myproject/FEATURE-8
	refs/remotes/origin/myproject/base
-----------------------------------------------------------
Fast-forwarding to: refs/conflicts/069594f00ab6213b53e1bc2c37305c812223c12d
Already up-to-date with refs/remotes/origin/myproject/FEATURE-1
Already up-to-date with refs/remotes/origin/myproject/FEATURE-2
Already up-to-date with refs/remotes/origin/myproject/FEATURE-3
Already up-to-date with refs/remotes/origin/myproject/FEATURE-4
Already up-to-date with refs/remotes/origin/myproject/FEATURE-5
Already up-to-date with refs/remotes/origin/myproject/FEATURE-6
Trying simple merge with refs/remotes/origin/myproject/FEATURE-7
Trying simple merge with refs/remotes/origin/myproject/FEATURE-8
Simple merge did not work, trying automatic merge.
Auto-merging auth/db/auth.php
Auto-merging user/lib.php
Already up-to-date with refs/remotes/origin/myproject/base
error: duplicate parent f851201f58662264ad7864dbbf8e2240ce7bf84a ignored
-----------------------------------------------------------
OCTOPUS SUCCESS
```

**Comment by dbaeli** [comment]
Is the conflict resolution push on origin ?

Dimitri BAELI

Le 15 nov. 2016 à 09:11, durzo notifications@github.com a écrit :

Hi, I'm a bit confused on the proper way to resolve conflicts.

I am merging 9 branches and there is a conflict between two. I created a conflict resolution using git conflict but octopus still fails unless i specify the resolution ref in my command line arguments:

$ git octopus origin/myproject/FEATURE-\* origin/myproject/base
Branches beeing merged :
    refs/remotes/origin/myproject/FEATURE-1
    refs/remotes/origin/myproject/FEATURE-2
    refs/remotes/origin/myproject/FEATURE-3
    refs/remotes/origin/myproject/FEATURE-4
    refs/remotes/origin/myproject/FEATURE-5
    refs/remotes/origin/myproject/FEATURE-6
    refs/remotes/origin/myproject/FEATURE-7
    refs/remotes/origin/myproject/FEATURE-8

##     refs/remotes/origin/myproject/base

Fast-forwarding to: refs/remotes/origin/myproject/FEATURE-1
Trying simple merge with refs/remotes/origin/myproject/FEATURE-2
Trying simple merge with refs/remotes/origin/myproject/FEATURE-3
Trying simple merge with refs/remotes/origin/myproject/FEATURE-4
Trying simple merge with refs/remotes/origin/myproject/FEATURE-5
Simple merge did not work, trying automatic merge.
Auto-merging lib/moodlelib.php
Trying simple merge with refs/remotes/origin/myproject/FEATURE-6
Simple merge did not work, trying automatic merge.
Auto-merging lib/moodlelib.php
Auto-merging lib/setuplib.php
ERROR: content conflict in lib/setuplib.php
Added local/filestorage/classes/file_storage/file_system.php in both, but differently.
ERROR: content conflict in local/filestorage/classes/file_storage/file_system.php
Added local/filestorage/lang/en/local_filestorage.php in both, but differently.
ERROR: content conflict in local/filestorage/lang/en/local_filestorage.php
Added local/logging/classes/logger.php in both, but differently.
ERROR: content conflict in local/logging/classes/logger.php
Added local/logging/classes/monolog/fluenthandler.php in both, but differently.
ERROR: content conflict in local/logging/classes/monolog/fluenthandler.php
Added local/logging/db/tasks.php in both, but differently.
ERROR: content conflict in local/logging/db/tasks.php
Added local/logging/lang/en/local_logging.php in both, but differently.
ERROR: content conflict in local/logging/lang/en/local_logging.php
Added local/logging/version.php in both, but differently.
ERROR: content conflict in local/logging/version.php
fatal: merge program failed
Applying conflict resolution 069594f00ab6213b53e1bc2c37305c812223c12d
Trying simple merge with refs/remotes/origin/myproject/FEATURE-7

## fatal: You need to resolve your current index first

Testing merges one by one with myproject/base...

merging refs/remotes/origin/myproject/FEATURE-1 ... SUCCESS
merging refs/remotes/origin/myproject/FEATURE-2 ... SUCCESS
merging refs/remotes/origin/myproject/FEATURE-3 ... SUCCESS
merging refs/remotes/origin/myproject/FEATURE-4 ... SUCCESS
merging refs/remotes/origin/myproject/FEATURE-5 ... SUCCESS
merging refs/remotes/origin/myproject/FEATURE-6 ... SUCCESS
merging refs/remotes/origin/myproject/FEATURE-7 ... SUCCESS

## merging refs/remotes/origin/myproject/FEATURE-8 ... SUCCESS

No conflicts found between myproject/base and the rest of the branches
OCTOPUS FAILED
If i use the conflict reference ID it works, but the documentation indicates that this isn't required, or is it ??

$ git octopus origin/myproject/FEATURE-\* origin/myproject/base 069594f00ab6213b53e1bc2c37305c812223c12d
Branches beeing merged :
    refs/conflicts/069594f00ab6213b53e1bc2c37305c812223c12d
    refs/remotes/origin/myproject/FEATURE-1
    refs/remotes/origin/myproject/FEATURE-2
    refs/remotes/origin/myproject/FEATURE-3
    refs/remotes/origin/myproject/FEATURE-4
    refs/remotes/origin/myproject/FEATURE-5
    refs/remotes/origin/myproject/FEATURE-6
    refs/remotes/origin/myproject/FEATURE-7
    refs/remotes/origin/myproject/FEATURE-8

##     refs/remotes/origin/myproject/base

Fast-forwarding to: refs/conflicts/069594f00ab6213b53e1bc2c37305c812223c12d
Already up-to-date with refs/remotes/origin/myproject/FEATURE-1
Already up-to-date with refs/remotes/origin/myproject/FEATURE-2
Already up-to-date with refs/remotes/origin/myproject/FEATURE-3
Already up-to-date with refs/remotes/origin/myproject/FEATURE-4
Already up-to-date with refs/remotes/origin/myproject/FEATURE-5
Already up-to-date with refs/remotes/origin/myproject/FEATURE-6
Trying simple merge with refs/remotes/origin/myproject/FEATURE-7
Trying simple merge with refs/remotes/origin/myproject/FEATURE-8
Simple merge did not work, trying automatic merge.
Auto-merging auth/db/auth.php
Auto-merging user/lib.php
Already up-to-date with refs/remotes/origin/myproject/base

## error: duplicate parent f851201f58662264ad7864dbbf8e2240ce7bf84a ignored

OCTOPUS SUCCESS

**Comment by durzo** [comment]
Yes

created using:

```
*** fix conflicts ***
$ git add -A
$ git conflict --continue
Conflict resolution created: refs/conflicts/069594f00ab6213b53e1bc2c37305c812223c12d
$ git push origin refs/conflicts/069594f00ab6213b53e1bc2c37305c812223c12d
Counting objects: 32, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 646 bytes | 0 bytes/s, done.
Total 6 (delta 5), reused 0 (delta 0)
To git@myserver:repo/myproject.git
 * [new branch]      refs/conflicts/069594f00ab6213b53e1bc2c37305c812223c12d -> refs/conflicts/069594f00ab6213b53e1bc2c37305c812223c12d
```

**Comment by apflieger** [comment]
I never thought of this usecase, funny :)
Conflict refs are not supposed to be used directly as an octopus argument. 
The problem here is that your conflict contains files that are 'added both sides but differently' which is a conflict case that 'git-conflict' doesn't handle
https://github.com/lesfurets/git-octopus/blob/master/src/lib/hash-conflict#L63 actually, git-conflict handles only the 'UU' case which means content conflict on existing files (Updated-Updated). 
There's no good reason for this to not be implemented. We just never had the use for it.

Giving the conflict ref as an argument works because it's like having a manual merge between the 2 branches
