### ISSUE TITLE
Need to create alias git-merge-index='git merge-index'

### ISSUE THREAD

**Issue by louis49** [lesfurets/git-octopus#3]
Bonjour,

Pour que git-octopus fonctionne correctement j'ai du créer un alias pour git-merge-index, sinon on a l'erreur : 
line 90: git-merge-index: command not found

Est-il possible d'avoir une version sans avoir à créer cet alias ?

Merci d'avance,

Benoît

**Comment by dbaeli** [comment]
Bonjour, quelle est votre version de git ?
Dimitri

**Comment by louis49** [comment]
Sur l'integ continue CircleCI il s'agit de la version :
git version 1.8.5.6

**Comment by dbaeli** [comment]
Il n'est pas possible de monter de version ?

**Comment by apflieger** [comment]
Je me rappelle  avoir eu l'erreur inverse "git merge-index not found" sur certains systèmes, peut etre windows.
je vais essayer de tirer ca au clair...

**Comment by louis49** [comment]
Malheureusement CircleCI ne me permet pas de mettre à jour git ;-(

**Comment by apflieger** [comment]
Ca vient du fait que tu utilises "git-octopus" et pas "git octopus" dans ton script,
Y a t'il une raison de ne pas passer par le binaire git ?
