### ISSUE TITLE
Unable to find common commit

### ISSUE THREAD

**Issue by YOUR1** [lesfurets/git-octopus#33]
Hi,

When i'm running `git octopus origin/features/* origin/master` i get the following error: `Unable to find common commit with refs/remotes/origin/features/<branch>`

Tree is as follow:
<img width="241" alt="screen shot 2017-04-05 at 12 15 15" src="https://cloud.githubusercontent.com/assets/3681016/24701113/9cba40ee-19f9-11e7-8444-c22492de4be1.png">

Is there anyway to fix this, and making the octopus merge succeed?

**Comment by apflieger** [comment]
Hi! Welcome :)

It seems that you are trying to merge histories that come from unrelated repos. 
Is the error clear for you ?
Is that a usual usecase for you ?

**Comment by apflieger** [comment]
This is not related to git-octopus though. If you are still trying to merge unrelated histories, don't hesitate to ask me, I can give you some hints ;)
Closing.
