### ISSUE TITLE
Multiple fast-forward error

### ISSUE THREAD

**Issue by danoliv** [lesfurets/git-octopus#37]
Hi, we have seen that when we have multiple branches that are in the same path and modify the same file the fast-forward does not work correctly.

In this case we have a branch feature1 that modify the file `testEntry` and the `feature2` branched from `feature1` that modify the same file. The tree is pretty straightforward:
```
feature2
|
feature1
|
master
```
But when we launch git-octopus and we have the following error:
```
Fast-forwarding to: refs/remotes/origin/feature1
Fast-forwarding to: refs/remotes/origin/feature2
2017/07/06 12:52:09 error: Entry 'testEntry' would be overwritten by merge. Cannot merge.
```

I added a branch `multiple_fast_forward` with a test `TestTwoBranchesFastForward` to try to reproduce the bug.
Thanks
Andrea

**Comment by apflieger** [comment]
I just released the fix https://github.com/lesfurets/git-octopus/releases/tag/v2.0-beta.3
